#! /bin/sh

mkdir -p /proc
mount -t proc none /proc

mkdir -p /dev
mount -t devtmpfs none /dev

mkdir -p /sys
mount -t sysfs none /sys

mount -a

# set hostname
echo "Setting hostname"
hostname devboard1

#remount everything, read/write
echo "Remounting root"
mount -o remount,rw /

# clear ethernet's IP
#echo "Bringing up eth0"
#ifconfig eth0 10.1.1.3
#ifconfig eth0 up

#setup dhcp
#echo "Launching udhcpc"
#/sbin/udhcpc -n -q -s /usr/share/udhcpc/default.script

echo "Configuring loopback device"
#ifconfig lo 127.0.0.1
ifup lo

# inetd startup
inetd

