/*
 * Copyright (C) 2017 Amlogic, Inc. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Description:
 * This file is automaticly generated by genregs.awk. Please do not edit it
 * Base files are ..
 *   ..
 *   ..
 * Tue Oct 22 15:28:48 CST 2013
 */
#ifndef __MACH_MESON8_REG_ADDR_H_
#define __MACH_MESON8_REG_ADDR_H_

#define DEMUX_X_OFFSET         0x50

#define TS_HIU1_CONFIG	(0x4e)
#define TS_TOP_CONFIG1	(0x4f)
#define STB_S2P2_CONFIG  (0xef)
#define STB_RECORDER2_CNTL	(0xee)
#define STB_TOP_CONFIG  (0xf0)
#define TS_TOP_CONFIG	(0xf1)
#define TS_FILE_CONFIG	(0xf2)
#define TS_PL_PID_INDEX (0xf3)
#define TS_PL_PID_DATA  (0xf4)
#define COMM_DESC_KEY0  (0xf5)
#define COMM_DESC_KEY1  (0xf6)
#define COMM_DESC_KEY_RW (0xf7)
#define CIPLUS_KEY0		(0xf8)
#define CIPLUS_KEY1		(0xf9)
#define CIPLUS_KEY2		(0xfa)
#define CIPLUS_KEY3		(0xfb)
#define CIPLUS_KEY_WR    (0xfc)
#define CIPLUS_CONFIG    (0xfd)
#define CIPLUS_ENDIAN    (0xfe)

#define ASYNC_FIFO_REG0 (0x0)
#define ASYNC_FIFO_REG1 (0x1)
#define ASYNC_FIFO_REG2 (0x2)
#define ASYNC_FIFO_REG3 (0x3)
#define ASYNC_FIFO_REG4 (0x4)
#define ASYNC_FIFO_REG5 (0x5)

#define PARSER_SUB_START_PTR (0x8a)
#define PARSER_SUB_END_PTR (0x8b)
#define PARSER_SUB_WP (0x8c)
#define PARSER_SUB_RP (0x8d)
#define PARSER_SUB_HOLE (0x8e)


#define STB_VERSION   (0x00)
#define STB_TEST_REG   (0x01)

#define FEC_INPUT_CONTROL   (0x2)
#define FEC_INPUT_DATA (0x03)
#define DEMUX_CONTROL (0x04)
#define FEC_SYNC_BYTE (0x05)

#define FM_WR_DATA (0x06)
#define FM_WR_ADDR (0x07)
#define MAX_FM_COMP_ADDR (0x08)

#define TS_HEAD_0 (0x09)
#define TS_HEAD_1 (0x0a)

#define OM_CMD_STATUS (0x0b)

#define OM_CMD_DATA (0x0c)
#define OM_CMD_DATA2 (0x0d)

#define SEC_BUFF_01_START (0x0e)
#define SEC_BUFF_23_START (0x0f)
#define SEC_BUFF_SIZE (0x10)
#define SEC_BUFF_BUSY (0x11)
#define SEC_BUFF_READY (0x12)
#define SEC_BUFF_NUMBER (0x13)


#define ASSIGN_PID_NUMBER (0x14)
#define VIDEO_STREAM_ID (0x15)
#define AUDIO_STREAM_ID (0x16)
#define SUB_STREAM_ID (0x17)
#define OTHER_STREAM_ID (0x18)
#define PCR90K_CTL (0x19)
#define PCR_DEMUX (0x1a)

#define VIDEO_PTS_DEMUX (0x1b)
#define VIDEO_DTS_DEMUX (0x1c)
#define AUDIO_PTS_DEMUX (0x1d)
#define SUB_PTS_DEMUX (0x1e)
#define STB_PTS_DTS_STATUS (0x1f)

#define STB_DEBUG_INDEX (0x20)
#define STB_DEBUG_DATAUT_O (0x21)

#define STBM_CTL_O (0x22)
#define STB_INT_STATUS (0x23)
#define DEMUX_ENDIAN (0x24)
#define TS_HIU_CTL (0x25)

#define SEC_BUFF_BASE (0x26)
#define DEMUX_MEM_REQ_EN (0x27)

#define VIDEO_PDTS_WR_PTR (0x28)
#define AUDIO_PDTS_WR_PTR (0x29)
#define SUB_WR_PTR (0x2a)

#define SB_START (0x2b)
#define SB_LAST_ADDR (0x2c)
#define SB_PES_WR_PTR (0x2d)
#define OTHER_WR_PTR (0x2e)

#define OB_START (0x2f)
#define OB_LAST_ADDR (0x30)
#define OB_PES_WR_PTR (0x31)
#define STB_INT_MASK (0x32)
#define VIDEO_SPLICING_CTL (0x33)
#define AUDIO_SPLICING_CTL (0x34)
#define TS_PACKAGE_BYTE_COUNT (0x35)

#define PES_STRONG_SYNC (0x36)

#define OM_DATA_RD_ADDR (0x37)
#define OM_DATA_RD (0x38)

#define SECTION_AUTO_STOP_3 (0x39)
#define SECTION_AUTO_STOP_2 (0x3a)
#define SECTION_AUTO_STOP_1 (0x3b)
#define SECTION_AUTO_STOP_0 (0x3c)

#define DEMUX_CHANNEL_RESET (0x3d)
#define DEMUX_SCRAMBLING_STATE (0x3e)
#define DEMUX_CHANNEL_ACTIVITY (0x3f)

#define DEMUX_STAMP_CTL (0x40)
#define DEMUX_VIDEO_STAMP_SYNC_0 (0x41)
#define DEMUX_VIDEO_STAMP_SYNC_1 (0x42)
#define DEMUX_AUDIO_STAMP_SYNC_0 (0x43)
#define DEMUX_AUDIO_STAMP_SYNC_1 (0x44)
#define DEMUX_SECTION_RESET (0x45)

/*from c_stb_define.h*/
#define COMM_DESC_2_CTL     (0xff) /*0x16ff*/

#define STB_OM_CTL (0x22) /* 0x1622*/

#define DEMUX_INPUT_TIMEOUT_C   (0x46)         /* 0x1646*/
/* bit[31] - no_match_reset_timeout_disable*/
/* bit[30:0] input_time_out_int_cnt (0 -- means disable) Wr-setting, Rd-count*/
#define DEMUX_INPUT_TIMEOUT     (0x47)         /* 0x1647*/

/* bit[31:0] - channel_packet_count_disable*/
#define DEMUX_PACKET_COUNT_C    (0x48)         /* 0x1648*/
/* bit[31] - no_match_packet_count_disable*/
/* bit[30:0] input_packet_count*/
#define DEMUX_PACKET_COUNT      (0x49)         /* 0x1649*/

/* bit[31:0] channel_record_enable*/
#define DEMUX_CHAN_RECORD_EN    (0x4a)         /* 0x164a*/

/* bit[31:0] channel_process_enable*/
#define DEMUX_CHAN_PROCESS_EN   (0x4b)         /* 0x164b*/

/* bit[31:24] small_sec_size ((n+1) * 256 Bytes)*/
/* bit[23:16] small_sec_rd_ptr */
/* bit[15:8]  small_sec_wr_ptr */
/* bit[7:2]   reserved*/
/* bit[1] small_sec_wr_ptr_wr_enable*/
/* bit[0] small_section_enable*/
#define DEMUX_SMALL_SEC_CTL     (0x4c)         /* 0x164c*/
/* bit[31:0] small_sec_start_addr*/
#define DEMUX_SMALL_SEC_ADDR    (0x4d)         /* 0x164d*/

#endif
