/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __REGISTERS_MESON_CPU_H
#define __REGISTERS_MESON_CPU_H

enum meson_cpuid_type_e {
	MESON_CPU_MAJOR_ID_M8B = 0x1B,
	MESON_CPU_MAJOR_ID_GXBB = 0x1F,
	MESON_CPU_MAJOR_ID_GXTVBB,
	MESON_CPU_MAJOR_ID_GXL,
	MESON_CPU_MAJOR_ID_GXM,
	MESON_CPU_MAJOR_ID_TXL,
	MESON_CPU_MAJOR_ID_TXLX,
	MESON_CPU_MAJOR_ID_AXG,
	MESON_CPU_MAJOR_ID_GXLX,
	MESON_CPU_MAJOR_ID_TXHD,
	MESON_CPU_MAJOR_ID_G12A,
	MESON_CPU_MAJOR_ID_G12B,
	MESON_CPU_MAJOR_ID_SM1 = 0x2B,
	MESON_CPU_MAJOR_ID_TL1 = 0x2E,
	MESON_CPU_MAJOR_ID_TM2,
	MESON_CPU_MAJOR_ID_C1,
	MESON_CPU_MAJOR_ID_SC2 = 0x32,
	MESON_CPU_MAJOR_ID_C2 = 0x33,
	MESON_CPU_MAJOR_ID_T5 = 0x34,
	MESON_CPU_MAJOR_ID_T5D = 0x35,
	MESON_CPU_MAJOR_ID_T7 = 0x36,
	MESON_CPU_MAJOR_ID_S4 = 0x37,
	MESON_CPU_MAJOR_ID_T3 = 0x38,
	MESON_CPU_MAJOR_ID_S4D = 0x3a,
	MESON_CPU_MAJOR_ID_T5W = 0x3b,
	MESON_CPU_MAJOR_ID_C3 = 0x3c,
	MESON_CPU_MAJOR_ID_S5 = 0x3e,
	MESON_CPU_MAJOR_ID_T5M = 0x41,
	MESON_CPU_MAJOR_ID_T3X = 0x42,
	MESON_CPU_MAJOR_ID_TXHD2 = 0x44,
	MESON_CPU_MAJOR_ID_S1A = 0x45,
	MESON_CPU_MAJOR_ID_S7 = 0x46,
	MESON_CPU_MAJOR_ID_S7D = 0x47,
	MESON_CPU_MAJOR_ID_S6 = 0x48,
	MESON_CPU_MAJOR_ID_UNKNOWN,
};

//TODO
static inline int get_cpu_type(void)
{
    return MESON_CPU_MAJOR_ID_GXL;
}

#endif
